/* jshint esversion: 6 */

export const NOTIFICATION_ADDED = 'NOTIFICATION_ADDED';
export const NOTIFICATION_ADD_ERROR = 'NOTIFICATION_ADD_ERROR';
export const NOTIFICATION_ADD_SUCCESS = 'NOTIFICATION_ADD_SUCCESS';
export const NOTIFICATION_ADD_WARNING = 'NOTIFICATION_ADD_WARNING';
