language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install -g jslint
  - npm install -g eslint

script:
  - npm run test 

after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
