language: node_js

node_js:
  - "node"

branches:
  only:
  - master

install:
  - npm install -g firebase-tools

script:
  - npm install
  - npm run lint 
  # - npm run test 

after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
