/* jshint esversion: 6 */

export const FIREBASE_FETCH_USER = 'FIREBASE_FETCH_USER';
export const FIREBASE_FETCH_USER_SUCCEEDED = 'FIREBASE_FETCH_USER_SUCCEEDED';
export const FIREBASE_FETCH_USER_FAILED = 'FIREBASE_FETCH_USER_FAILED';
export const FIREBASE_LOGIN_WITH_PROVIDER = 'FIREBASE_LOGIN_WITH_PROVIDER';
export const FIREBASE_REGISTER_WITH_EMAIL_PASSWORD = 'FIREBASE_LOGIN_WITH_EMAIL_PASSWORD';
export const FIREBASE_LOGIN_WITH_EMAIL_PASSWORD = 'FIREBASE_LOGIN_WITH_EMAIL_PASSWORD';
