/* jshint esversion: 6 */

export const FIREBASE_ACKNOWLEDGE_OPERATION = 'FIREBASE_ACKNOWLEDGE_OPERATION';

export const FIREBASE_FETCH_USER = 'FIREBASE_FETCH_USER';
export const FIREBASE_FETCH_USER_SUCCEEDED = 'FIREBASE_FETCH_USER_SUCCEEDED';
export const FIREBASE_FETCH_USER_FAILED = 'FIREBASE_FETCH_USER_FAILED';

export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD';
export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED';

export const FIREBASE_SIGNUP_WITH_PROVIDER = 'FIREBASE_SIGNUP_WITH_PROVIDER';
export const FIREBASE_SIGNUP_WITH_PROVIDER_SUCCEEDED = 'FIREBASE_SIGNUP_WITH_PROVIDER_SUCCEEDED';
export const FIREBASE_SIGNUP_WITH_PROVIDER_FAILED = 'FIREBASE_SIGNUP_WITH_PROVIDER_FAILED';

export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD';
export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED';

export const FIREBASE_SIGNIN_WITH_PROVIDER = 'FIREBASE_SIGNIN_WITH_PROVIDER';
export const FIREBASE_SIGNIN_WITH_PROVIDER_SUCCEEDED = 'FIREBASE_SIGNIN_WITH_PROVIDER_SUCCEEDED';
export const FIREBASE_SIGNIN_WITH_PROVIDER_FAILED = 'FIREBASE_SIGNIN_WITH_PROVIDER_FAILED';

export const FIREBASE_SIGNOUT = 'FIREBASE_SIGNOUT';
export const FIREBASE_SIGNOUT_SUCCEEDED = 'FIREBASE_SIGNOUT_SUCCEEDED';
export const FIREBASE_SIGNOUT_FAILED = 'FIREBASE_SIGNOUT_FAILED';

export const FIREBASE_RESET_PASSWORD = 'FIREBASE_RESET_PASSWORD';
export const FIREBASE_RESET_PASSWORD_SUCCEEDED = 'FIREBASE_RESET_PASSWORD_SUCCEEDED';
export const FIREBASE_RESET_PASSWORD_FAILED = 'FIREBASE_RESET_PASSWORD_FAILED';

export const FIREBASE_UPDATE_PASSWORD = 'FIREBASE_UPDATE_PASSWORD';
export const FIREBASE_UPDATE_PASSWORD_SUCCEEDED = 'FIREBASE_UPDATE_PASSWORD_SUCCEEDED';
export const FIREBASE_UPDATE_PASSWORD_FAILED = 'FIREBASE_UPDATE_PASSWORD_FAILED';

export const FIREBASE_UPDATE_USER_PUBLIC_PROFILE = 'FIREBASE_UPDATE_USER_PUBLIC_PROFILE';
export const FIREBASE_UPDATE_USER_PUBLIC_PROFILE_SUCCEEDED = 'FIREBASE_UPDATE_USER_PUBLIC_PROFILE_SUCCEEDED';
export const FIREBASE_UPDATE_USER_PUBLIC_PROFILE_FAILED = 'FIREBASE_UPDATE_USER_PUBLIC_PROFILE_FAILED';
