/* jshint esversion: 6 */

export const FIREBASE_FETCH_USER = 'FIREBASE_FETCH_USER';
export const FIREBASE_FETCH_USER_SUCCEEDED = 'FIREBASE_FETCH_USER_SUCCEEDED';
export const FIREBASE_FETCH_USER_FAILED = 'FIREBASE_FETCH_USER_FAILED';

export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD';
export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED = 'FIREBASE_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED';

export const FIREBASE_SIGNUP_WITH_PROVIDER = 'FIREBASE_SIGNUP_WITH_PROVIDER';
export const FIREBASE_SIGNUP_WITH_PROVIDER_SUCCEEDED = 'FIREBASE_SIGNUP_WITH_PROVIDER_SUCCEEDED';
export const FIREBASE_SIGNUP_WITH_PROVIDER_FAILED = 'FIREBASE_SIGNUP_WITH_PROVIDER_FAILED';

export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD';
export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED = 'FIREBASE_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED';

export const FIREBASE_SIGNIN_WITH_PROVIDER = 'FIREBASE_SIGNIN_WITH_PROVIDER';
export const FIREBASE_SIGNIN_WITH_PROVIDER_SUCCEEDED = 'FIREBASE_SIGNIN_WITH_PROVIDER_SUCCEEDED';
export const FIREBASE_SIGNIN_WITH_PROVIDER_FAILED = 'FIREBASE_SIGNIN_WITH_PROVIDER_FAILED';

export const FIREBASE_LOGOUT = 'FIREBASE_LOGOUT';
export const FIREBASE_LOGOUT_SUCCEEDED = 'FIREBASE_LOGOUT_SUCCEEDED';
export const FIREBASE_LOGOUT_FAILED = 'FIREBASE_LOGOUT_FAILED';
