/* jshint esversion: 6 */

export const USER_ACCESS_ACKNOWLEDGE_OPERATION = 'USER_ACCESS_ACKNOWLEDGE_OPERATION';

export const USER_ACCESS_FETCH_USER = 'USER_ACCESS_FETCH_USER';
export const USER_ACCESS_FETCH_USER_SUCCEEDED = 'USER_ACCESS_FETCH_USER_SUCCEEDED';
export const USER_ACCESS_FETCH_USER_FAILED = 'USER_ACCESS_FETCH_USER_FAILED';

export const USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD = 'USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD';
export const USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED =
  'USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED = 'USER_ACCESS_SIGNUP_WITH_EMAIL_AND_PASSWORD_FAILED';

export const USER_ACCESS_SIGNUP_WITH_PROVIDER = 'USER_ACCESS_SIGNUP_WITH_PROVIDER';
export const USER_ACCESS_SIGNUP_WITH_PROVIDER_SUCCEEDED = 'USER_ACCESS_SIGNUP_WITH_PROVIDER_SUCCEEDED';
export const USER_ACCESS_SIGNUP_WITH_PROVIDER_FAILED = 'USER_ACCESS_SIGNUP_WITH_PROVIDER_FAILED';

export const USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD = 'USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD';
export const USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED =
  'USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD_SUCCEEDED';
export const USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED = 'USER_ACCESS_SIGNIN_WITH_EMAIL_AND_PASSWORD_FAILED';

export const USER_ACCESS_SIGNIN_WITH_PROVIDER = 'USER_ACCESS_SIGNIN_WITH_PROVIDER';
export const USER_ACCESS_SIGNIN_WITH_PROVIDER_SUCCEEDED = 'USER_ACCESS_SIGNIN_WITH_PROVIDER_SUCCEEDED';
export const USER_ACCESS_SIGNIN_WITH_PROVIDER_FAILED = 'USER_ACCESS_SIGNIN_WITH_PROVIDER_FAILED';

export const USER_ACCESS_SIGNOUT = 'USER_ACCESS_SIGNOUT';
export const USER_ACCESS_SIGNOUT_SUCCEEDED = 'USER_ACCESS_SIGNOUT_SUCCEEDED';
export const USER_ACCESS_SIGNOUT_FAILED = 'USER_ACCESS_SIGNOUT_FAILED';

export const USER_ACCESS_RESET_PASSWORD = 'USER_ACCESS_RESET_PASSWORD';
export const USER_ACCESS_RESET_PASSWORD_SUCCEEDED = 'USER_ACCESS_RESET_PASSWORD_SUCCEEDED';
export const USER_ACCESS_RESET_PASSWORD_FAILED = 'USER_ACCESS_RESET_PASSWORD_FAILED';

export const USER_ACCESS_UPDATE_PASSWORD = 'USER_ACCESS_UPDATE_PASSWORD';
export const USER_ACCESS_UPDATE_PASSWORD_SUCCEEDED = 'USER_ACCESS_UPDATE_PASSWORD_SUCCEEDED';
export const USER_ACCESS_UPDATE_PASSWORD_FAILED = 'USER_ACCESS_UPDATE_PASSWORD_FAILED';

export const USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE = 'USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE';
export const USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE_SUCCEEDED = 'USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE_SUCCEEDED';
export const USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE_FAILED = 'USER_ACCESS_UPDATE_USER_PUBLIC_PROFILE_FAILED';

export const USER_ACCESS_SEND_EMAIL_VERIFICATION = 'USER_ACCESS_SEND_EMAIL_VERIFICATION';
export const USER_ACCESS_SEND_EMAIL_VERIFICATION_SUCCEEDED = 'USER_ACCESS_SEND_EMAIL_VERIFICATION_SUCCEEDED';
export const USER_ACCESS_SEND_EMAIL_VERIFICATION_FAILED = 'USER_ACCESS_SEND_EMAIL_VERIFICATION_FAILED';
